name: lst-dev
channels:
  - conda-forge
dependencies:
  - python=3.11
  - numpy
  - astropy=6
  - pip
  - ctapipe=0.25.0
  - ctapipe_io_lst >=0.26.1
  - ctaplot~=0.6.4
  - gammapy=1.2
  - h5py
  - ipython
  - jupyter
  - matplotlib=3.7
  - notebook
  - iminuit>=2
  - joblib~=1.2.0
  - toml
  - protozfits=2.6
  - pyparsing
  - scipy <1.14
  - scikit-learn=1.2
  - sphinx
  - sphinx-automodapi
  - sphinx_rtd_theme
  - sphinx-argparse
  - sphinxcontrib-mermaid
  - nbsphinx
  - numba
  - numpydoc
  - pandas>=2
  - pymongo
  - seaborn
  - pytest
  - pyirf~=0.10.0
